baseURL = "https://sheheemmulakkal.github.io/hugo-personal-blog/"
languageCode = 'en-us'
title = 'Muhammed Sheheem'
theme  = 'hugo-ink'

[params]
	#subtitle = "Personal blog website"

	# Optional 64x64 avatar image.
	avatar = "/hugo-personal-blog/profile"


	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	#customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	#customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	#customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blogs"
url = "/blogs"
weight = 2

[[menu.main]]
name = "Gallery"
url = "/gallery"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/sheheemmulakkal"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
